service: open-data-germany-ckan

provider:
  name: aws
  runtime: python2.7
  profile: prototypefund
  timeout: 300

package:
  include:
    - od/lib/python2.7/site-packages
    - stats/offene_daten.py
    - stats/utils.py
    - handlers.py
  exclude:
    - od

functions:
  organisations:
    handler: orgs.organisations
  single_city:
    handler: handlers.single_city
  compute_ranks:
    handler: handlers.compute_ranks
  get_all_cities:
    handler: handlers.get_all_cities
    events:
      - schedule:
        name: organisations-schedule
        description: 'Schedule for Org data updates'
        rate: cron(0 2 * * ? *)
